### ISSUE TITLE
It would be nice if users can directly pass a string or bigarray parameter

### ISSUE THREAD

**Issue by UnixJunkie** [whitequark/ocaml-lz4#5]
instead of asking for a length parameter and allocating a fresh buffer each time

**Comment by UnixJunkie** [comment]
The parameters should be: buff, offset, length.
with the meaning read/write from/to buff at offset and up to length

**Comment by whitequark** [comment]
Patches accepted. It should be very easy since it only requires modifying OCaml code here.

**Comment by UnixJunkie** [comment]
make all --> https://gist.github.com/UnixJunkie/e17701a8c4afe42f3f05

**Comment by whitequark** [comment]
Seems like a wrong ctypes version... which one do you have?

**Comment by UnixJunkie** [comment]
# opam info ctypes
package: ctypes
version: 0.4.1

**Comment by whitequark** [comment]
Try 0.3.4, it should work for now. I will fix the issue later.

**Comment by UnixJunkie** [comment]
With ctypes.0.3.4 it compiles well.
But I'm affraid we need additional support from ctypes:
https://github.com/ocamllabs/ocaml-ctypes/issues/301

**Comment by UnixJunkie** [comment]
I'll send a patch soon

**Comment by UnixJunkie** [comment]
https://github.com/whitequark/ocaml-lz4/pull/6

**Comment by UnixJunkie** [comment]
I'd be happy to get an e-mail when there is a new release in opam.
Thanks a lot for this library !

**Comment by whitequark** [comment]
I have now realized two issues with your PR.

  * With Bigarray, the `_at` functions are not in fact needed. You can pass a slice of a Bigarray using [Bigarray.Array1.sub](http://caml.inria.fr/pub/docs/manual-ocaml/libref/Bigarray.Array1.html#VALsub).
  * Also, your functions provide the way to seek into _destination_ buffer, but not _source_ buffer, which in my opinion is actually less useful, especially in the decompression case, since your compressed data will probably originally reside in a network buffer or something.

I am not sure if there is any point in extending the interface solely for the String functions, given that performance-sensitive code should use Bigarrays anyway. I have reverted the changes for now. Feel free to suggest improvements that would alleviate the points above.

**Comment by UnixJunkie** [comment]
OK, I will try to use Bigarray.sub in my code then
